-- Seed data for apply_commanders. Regenerate with:
--   node scripts/build-apply-commanders-sql.mjs
--
-- Idempotent: uses INSERT ... ON CONFLICT (id) DO UPDATE so re-running with a
-- refreshed txt just applies the diff. Legacy ids from the TS archive are
-- preserved where names match, keeping past leader_applications lookups alive.

insert into public.apply_commanders (id, name, specialties, rarity, image_url, sort_order) values
  ('alexander-the-great', 'Alexander the Great', ARRAY['Infantry','Versatility','Attack']::text[], 'legendary', null, 0),
  ('cao-cao', 'Cao Cao', ARRAY['Cavalry','Peacekeeping','Mobility']::text[], 'legendary', null, 1),
  ('charlemagne', 'Charlemagne', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 2),
  ('cleopatra', 'Cleopatra', ARRAY['Integration','Gathering','Support']::text[], 'legendary', null, 3),
  ('edward-of-woodstock', 'Edward of Woodstock', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 4),
  ('el-cid', 'El Cid', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 5),
  ('artemisia', 'Artemisia', ARRAY['Archer','Garrison','Defense']::text[], 'legendary', null, 6),
  ('frederick-i', 'Frederick I', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 7),
  ('richard-i', 'Richard I', ARRAY['Infantry','Garrison','Defense']::text[], 'legendary', null, 8),
  ('aethelflaed', 'Aethelflaed', ARRAY['Leadership','Peacekeeping','Support']::text[], 'legendary', null, 9),
  ('mulan', 'Mulan', ARRAY['Integration','Peacekeeping','Support']::text[], 'legendary', null, 10),
  ('emperor-leonidas', 'Emperor Leonidas', ARRAY['Infantry','Versatility','Defense']::text[], 'legendary', null, 11),
  ('charles-martel', 'Charles Martel', ARRAY['Infantry','Garrison','Defense']::text[], 'legendary', null, 12),
  ('guan-yu', 'Guan Yu', ARRAY['Infantry','Conquering','Skill']::text[], 'legendary', null, 13),
  ('attila', 'Attila', ARRAY['Cavalry','Conquering','Attack']::text[], 'legendary', null, 14),
  ('chandragupta', 'Chandragupta', ARRAY['Cavalry','Conquering','Skill']::text[], 'legendary', null, 15),
  ('hannibal-barca', 'Hannibal Barca', ARRAY['Leadership','Conquering','Defense']::text[], 'legendary', null, 16),
  ('constantine', 'Constantine', ARRAY['Infantry','Garrison','Support']::text[], 'legendary', null, 17),
  ('william-i', 'William I', ARRAY['Cavalry','Versatility','Attack']::text[], 'legendary', null, 18),
  ('takeda-shingen', 'Takeda Shingen', ARRAY['Cavalry','Versatility','Mobility']::text[], 'legendary', null, 19),
  ('harald-sigurdsson', 'Harald Sigurdsson', ARRAY['Infantry','Conquering','Skill']::text[], 'legendary', null, 20),
  ('lu-bu', 'Lu Bu', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 21),
  ('theodora', 'Theodora', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 22),
  ('genghis-khan', 'Genghis Khan', ARRAY['Cavalry','Versatility','Skill']::text[], 'legendary', null, 23),
  ('ishida-mitsunari', 'Ishida Mitsunari', ARRAY['Integration','Gathering','Support']::text[], 'legendary', null, 24),
  ('minamoto-no-yoshitsune', 'Minamoto no Yoshitsune', ARRAY['Cavalry','Peacekeeping','Skill']::text[], 'legendary', null, 25),
  ('julius-caesar', 'Julius Caesar', ARRAY['Leadership','Siege','Attack']::text[], 'legendary', null, 26),
  ('mehmed-ii', 'Mehmed II', ARRAY['Leadership','Conquering','Skill']::text[], 'legendary', null, 27),
  ('ramesses-ii', 'Ramesses II', ARRAY['Archer','Versatility','Attack']::text[], 'legendary', null, 28),
  ('saladin', 'Saladin', ARRAY['Cavalry','Conquering','Support']::text[], 'legendary', null, 29),
  ('seondeok', 'Seondeok', ARRAY['Integration','Gathering','Attack']::text[], 'legendary', null, 30),
  ('tomyris', 'Tomyris', ARRAY['Archer','Conquering','Attack']::text[], 'legendary', null, 31),
  ('wu-zetian', 'Wu Zetian', ARRAY['Leadership','Garrison','Support']::text[], 'legendary', null, 32),
  ('yi-seong-gye', 'Yi Seong Gye', ARRAY['Archer','Garrison','Garrison']::text[], 'legendary', null, 33),
  ('yi-sun-sin', 'Yi Sun-Sin', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 34),
  ('zenobia', 'Zenobia', ARRAY['Infantry','Garrison','Support']::text[], 'legendary', null, 35),
  ('lapu-lapu', 'Lapu Lapu', ARRAY['Leadership','Garrison','Skill']::text[], 'legendary', null, 36),
  ('gonzalo-de-cordoba', 'Gonzalo de Cordoba', ARRAY['Engineering','Versatility','Attack']::text[], 'legendary', null, 37),
  ('gajah-mada', 'Gajah Mada', ARRAY['Engineering','Versatility','Defense']::text[], 'legendary', null, 38),
  ('ashurbanipal', 'Ashurbanipal', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 39),
  ('hermann-prime', 'Hermann Prime', ARRAY['Archer','Versatility','Support']::text[], 'legendary', null, 40),
  ('justinian-i', 'Justinian I', ARRAY['Cavalry','Conquering','Support']::text[], 'legendary', null, 41),
  ('gorgo', 'Gorgo', ARRAY['Infantry','Garrison','Defense']::text[], 'legendary', null, 42),
  ('pericles', 'Pericles', ARRAY['Infantry','Garrison','Support']::text[], 'epic', null, 43),
  ('dido', 'Dido', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 44),
  ('huo-qubing', 'Huo Qubing', ARRAY['Cavalry','Versatility','Skill']::text[], 'legendary', null, 45),
  ('pyrrhus', 'Pyrrhus', ARRAY['Infantry','Versatility','Defense']::text[], 'legendary', null, 46),
  ('margaret-i', 'Margaret I', ARRAY['Engineering','Versatility','Support']::text[], 'legendary', null, 47),
  ('heraclius', 'Heraclius', ARRAY['Leadership','Garrison','Defense']::text[], 'legendary', null, 48),
  ('zhuge-liang', 'Zhuge Liang', ARRAY['Archer','Skill','Versatility']::text[], 'legendary', null, 49),
  ('babur', 'Babur', ARRAY['Engineering','Versatility','Attack']::text[], 'legendary', null, 50),
  ('joan-of-arc-prime', 'Joan of Arc Prime', ARRAY['Cavalry','Versatility','Support']::text[], 'legendary', null, 51),
  ('jan-zizka', 'Jan Zizka', ARRAY['Cavalry','Garrison','Skill']::text[], 'legendary', null, 52),
  ('sargon-the-great', 'Sargon the Great', ARRAY['Infantry','Skill','Versatility']::text[], 'legendary', null, 53),
  ('tariq-ibn-ziyad', 'Tariq ibn Ziyad', ARRAY['Infantry','Conquering','Defense']::text[], 'legendary', null, 54),
  ('boudica-prime', 'Boudica Prime', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 55),
  ('henry-v', 'Henry V', ARRAY['Archer','Conquering','Support']::text[], 'legendary', null, 56),
  ('thutmose-iii', 'Thutmose III', ARRAY['Archer','Versatility','Support']::text[], 'legendary', null, 57),
  ('flavius-aetius', 'Flavius Aetius', ARRAY['Infantry','Garrison','Skill']::text[], 'legendary', null, 58),
  ('baibars', 'Baibars', ARRAY['Cavalry','Conquering','Skill']::text[], 'epic', null, 59),
  ('belisarius', 'Belisarius', ARRAY['Cavalry','Peacekeeping','Mobility']::text[], 'epic', null, 60),
  ('boudica', 'Boudica', ARRAY['Integration','Peacekeeping','Skill']::text[], 'epic', null, 61),
  ('diaochan', 'Diaochan', ARRAY['Integration','Peacekeeping','Support']::text[], 'epic', null, 62),
  ('hermann', 'Hermann', ARRAY['Archer','Garrison','Skill']::text[], 'epic', null, 63),
  ('joan-of-arc', 'Joan of Arc', ARRAY['Integration','Gathering','Support']::text[], 'epic', null, 64),
  ('keira', 'Keira', ARRAY['Archer','Peacekeeping','Skill']::text[], 'epic', null, 65),
  ('kusunoki-masashige', 'Kusunoki Masashige', ARRAY['Archer','Garrison','Skill']::text[], 'epic', null, 66),
  ('lohar', 'Lohar', ARRAY['Integration','Peacekeeping','Support']::text[], 'epic', null, 67),
  ('matilda-of-flanders', 'Matilda of Flanders', ARRAY['Integration','Gathering','Defense']::text[], 'epic', null, 68),
  ('osman-i', 'Osman I', ARRAY['Leadership','Conquering','Skill']::text[], 'epic', null, 69),
  ('pelagius', 'Pelagius', ARRAY['Cavalry','Garrison','Skill']::text[], 'epic', null, 70),
  ('scipio-africanus', 'Scipio Africanus', ARRAY['Leadership','Conquering','Attack']::text[], 'epic', null, 71),
  ('sun-tzu', 'Sun Tzu', ARRAY['Infantry','Garrison','Skill']::text[], 'epic', null, 72),
  ('imhotep', 'Imhotep', ARRAY['Archer','Garrison','Support']::text[], 'epic', null, 73),
  ('bjorn-ironside', 'Bjorn Ironside', ARRAY['Infantry','Conquering','Skill']::text[], 'epic', null, 74),
  ('eulji-mundeok', 'Eulji Mundeok', ARRAY['Infantry','Garrison','Attack']::text[], 'epic', null, 75),
  ('sarka', 'Šárka', ARRAY['Integration','Gathering','Skill']::text[], 'elite', null, 76),
  ('lancelot', 'Lancelot', ARRAY['Cavalry','Versatility','Mobility']::text[], 'elite', null, 77),
  ('tomoe-gozen', 'Tomoe Gozen', ARRAY['Archer','Versatility','Attack']::text[], 'elite', null, 78),
  ('gaius-marius', 'Gaius Marius', ARRAY['Leadership','Gathering','Skill']::text[], 'elite', null, 79),
  ('constance', 'Constance', ARRAY['Integration','Gathering','Skill']::text[], 'elite', null, 80),
  ('markswoman', 'Markswoman', ARRAY['Archer','Peacekeeping','Skill']::text[], 'elite', null, 81),
  ('dragon-lancer', 'Dragon Lancer', ARRAY['Cavalry','Peacekeeping','Skill']::text[], 'elite', null, 82),
  ('city-keeper', 'City Keeper', ARRAY['Infantry','Versatility','Attack']::text[], 'elite', null, 83),
  ('centurion', 'Centurion', ARRAY['Integration','Gathering','Attack']::text[], 'elite', null, 84),
  ('xiang-yu', 'Xiang Yu', ARRAY['Cavalry','Conquering','Skill']::text[], 'legendary', null, 85),
  ('nebuchadnezzar-ii', 'Nebuchadnezzar II', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 86),
  ('gilgamesh', 'Gilgamesh', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 87),
  ('pakal-ii', 'Pakal II', ARRAY['Infantry','Conquering','Defense']::text[], 'legendary', null, 88),
  ('cyrus-the-great', 'Cyrus the Great', ARRAY['Archer','Versatility','Attack']::text[], 'legendary', null, 89),
  ('trajan', 'Trajan', ARRAY['Infantry','Gathering','Attack']::text[], 'legendary', null, 90),
  ('cheok-jun-gyeong', 'Cheok Jun-Gyeong', ARRAY['Infantry','Versatility','Attack']::text[], 'legendary', null, 91),
  ('honda-tadakatsu', 'Honda Tadakatsu', ARRAY['Leadership','Versatility','Skill']::text[], 'legendary', null, 92),
  ('bertrand-du-guesclin', 'Bertrand du Guesclin', ARRAY['Cavalry','Conquering','Defense']::text[], 'legendary', null, 93),
  ('alexander-nevsky', 'Alexander Nevsky', ARRAY['Cavalry','Versatility','Skill']::text[], 'legendary', null, 94),
  ('suleiman-i', 'Suleiman I', ARRAY['Leadership','Conquering','Attack']::text[], 'legendary', null, 95),
  ('ragnar-lodbrok', 'Ragnar Lodbrok', ARRAY['Leadership','Conquering','Attack']::text[], 'legendary', null, 96),
  ('jadwiga', 'Jadwiga', ARRAY['Cavalry','Garrison','Mobility']::text[], 'legendary', null, 97),
  ('choe-yeong', 'Choe Yeong', ARRAY['Archer','Garrison','Defense']::text[], 'legendary', null, 98),
  ('shajar-al-durr', 'Shajar al-Durr', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 99),
  ('belisarius-prime', 'Belisarius Prime', ARRAY['Cavalry','Versatility','Mobility']::text[], 'legendary', null, 100),
  ('eleanor-of-aquitaine', 'Eleanor of Aquitaine', ARRAY['Cavalry','Garrison','Defense']::text[], 'legendary', null, 101),
  ('william-wallace', 'William Wallace', ARRAY['Infantry','Versatility','Smite']::text[], 'legendary', null, 102),
  ('scipio-aemilianus', 'Scipio Aemilianus', ARRAY['Infantry','Conquering','Smite']::text[], 'legendary', null, 103),
  ('catherine-de-medici', 'Catherine de'' Medici', ARRAY['Engineering','Versatility','Skill']::text[], 'epic', null, 104),
  ('narses', 'Narses', ARRAY['Engineering','Versatility','Defense']::text[], 'epic', null, 105),
  ('john-hunyadi', 'John Hunyadi', ARRAY['Engineering','Versatility','Support']::text[], 'legendary', null, 106),
  ('stephen-iii', 'Stephen III', ARRAY['Engineering','Versatility','Skill']::text[], 'legendary', null, 107),
  ('ragnar-lodbrok-prime', 'Ragnar Lodbrok Prime', ARRAY['Leadership','Versatility','Support']::text[], 'legendary', null, 108),
  ('philip-ii', 'Philip II', ARRAY['Leadership','Versatility','Support']::text[], 'legendary', null, 109),
  ('wak-chanil-ajaw', 'Wak Chanil Ajaw', ARRAY['Integration','Gathering','Defense']::text[], 'epic', null, 110),
  ('siyaj-kak', 'Siyaj K''ak''', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 111),
  ('subutai', 'Subutai', ARRAY['Cavalry','Conquering','Combo']::text[], 'legendary', null, 112),
  ('shapur', 'Shapur', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 113),
  ('qin-shi-huang', 'Qin Shi Huang', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 114),
  ('tokugawa-ieyasu', 'Tokugawa Ieyasu', ARRAY['Infantry','Garrison','Smite']::text[], 'legendary', null, 115),
  ('bai-qi', 'Bai Qi', ARRAY['Infantry','Versatility','Smite']::text[], 'legendary', null, 116),
  ('afonso', 'Afonso', ARRAY['Engineering','Versatility','Support']::text[], 'legendary', null, 117),
  ('matthias', 'Matthias', ARRAY['Leadership','Garrison','Attack']::text[], 'legendary', null, 118),
  ('mary', 'Mary', ARRAY['Engineering','Versatility','Skill']::text[], 'legendary', null, 119),
  ('archimedes', 'Archimedes', ARRAY['Engineering','Versatility','Defense']::text[], 'legendary', null, 120),
  ('casimir', 'Casimir', ARRAY['Integration','Gathering','Defense']::text[], 'legendary', null, 121),
  ('pepin', 'Pepin', ARRAY['Integration','Gathering','Support']::text[], 'legendary', null, 122),
  ('sun-tzu-prime', 'Sun Tzu Prime', ARRAY['Infantry','Versatility','Smite']::text[], 'legendary', null, 123),
  ('ivar-the-boneless', 'Ivar the Boneless', ARRAY['Infantry','Conquering','Defense']::text[], 'legendary', null, 124),
  ('gang-gamchan', 'Gang Gamchan', ARRAY['Cavalry','Versatility','Combo']::text[], 'legendary', null, 125),
  ('hector', 'Hector', ARRAY['Leadership','Versatility','Support']::text[], 'legendary', null, 126),
  ('achilles', 'Achilles', ARRAY['Cavalry','Versatility','Combo']::text[], 'legendary', null, 127),
  ('elizabeth-i', 'Elizabeth I', ARRAY['Engineering','Versatility','Skill']::text[], 'legendary', null, 128),
  ('vercingetorix', 'Vercingetorix', ARRAY['Leadership','Versatility','Support']::text[], 'legendary', null, 129),
  ('hayam-wuruk', 'Hayam Wuruk', ARRAY['Archer','Garrison','Skill']::text[], 'legendary', null, 130),
  ('alp-arslan', 'Alp Arslan', ARRAY['Archer','Versatility','Skill']::text[], 'legendary', null, 131),
  ('david-iv', 'David IV', ARRAY['Cavalry','Garrison','Defense']::text[], 'legendary', null, 132),
  ('arthur-pendragon', 'Arthur Pendragon', ARRAY['Cavalry','Versatility','Skill']::text[], 'legendary', null, 133),
  ('liu-che', 'Liu Che', ARRAY['Infantry','Conquering','Attack']::text[], 'legendary', null, 134),
  ('scipio-prime', 'Scipio Africanus Prime', ARRAY['Leadership','Conquering','Attack']::text[], 'legendary', null, 135),
  ('amanitore', 'Amanitore', ARRAY['Archer','Conquering','Skill']::text[], 'legendary', null, 136),
  ('sargon-of-akkad', 'Sargon of Akkad', ARRAY['Infantry','Conquering','Attack']::text[], 'legendary', null, 137),
  ('moctezuma-i', 'Moctezuma I', ARRAY['Integration','Peacekeeping','Skill']::text[], 'legendary', null, 138),
  ('william-marshal', 'William Marshal', ARRAY['Cavalry','Conquering','Combo']::text[], 'legendary', null, 139),
  ('ivan-iv', 'Ivan IV', ARRAY['Cavalry','Versatility','Combo']::text[], 'legendary', null, 140)
on conflict (id) do update set
  name = excluded.name,
  specialties = excluded.specialties,
  rarity = excluded.rarity,
  image_url = excluded.image_url,
  sort_order = excluded.sort_order,
  updated_at = now();
